---

    -   name: Add MariaDB - CentOS 7
        lineinfile:
            path: /etc/yum.repos.d/MariaDB10.repo
            line: "{{ item }}"
            create: yes
        loop:
            - "[mariadb]"
            - name = MariaDB
            - baseurl = http://yum.mariadb.org/10.1/centos7-amd64
            - gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
            - gpgcheck=1
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    # -   name: Remove old entries - CentOS 7
    #     command: yum remove mariadb-server mariadb mariadb-libs -y
    #     when: 
    #         - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: CleanUP cache - CentOS 7
        command: yum clean all
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Initiate Mariadb - CentOS 7
        yum: 
            name: "{{ item }}"
            state: present
        loop:
            - MariaDB-server 
            - MariaDB-client 
            - MySQL-python
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Start the MYSQL service - CentOS 7
        service:
            name: mariadb
            enabled: yes
            state: started
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Download Zabbix - Ubuntu 18
        get_url:
            url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+bionic_all.deb
            dest: /tmp/zabbix-release_{{ zabbix_version }}-1+bionic_all.deb
        when: 
            - os_check.stdout | regex_search("Ubuntu 18")

    -   name: Download Zabbix - Ubuntu 20
        get_url:
            url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+focal_all.deb
            dest: /tmp/zabbix-release_{{ zabbix_version }}-1+focal_all.deb
        when: 
            - os_check.stdout | regex_search("Ubuntu 20") 

    -   name: Set SELinux 0
        command: setenforce 0
        when: 
            - os_check.stdout | regex_search("CentOS") 

    -   name: Put SELinux in permissive mode, logging actions that would be blocked.
        selinux:
            policy: targeted
            state: permissive
        when: 
            - os_check.stdout | regex_search("CentOS") 


    -   name: Download Zabbix - CentOS 7
        get_url:
            url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/7/x86_64/zabbix-release-{{ zabbix_version }}-1.el7.noarch.rpm
            dest: /tmp/zabbix-release-{{ zabbix_version }}-1.el7.noarch.rpm
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7") 

    -   name: Download Zabbix - CentOS 8
        get_url:
            url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/8/x86_64/zabbix-release-{{ zabbix_version }}-1.el8.noarch.rpm
            dest: /tmp/zabbix-release-{{ zabbix_version }}-1.el8.noarch.rpm
        when: 
            - os_check.stdout | regex_search("CentOS Linux 8") 

    -   name: Install Zabbix
        command: dpkg -i /tmp/zabbix-release_{{ zabbix_version }}-1+bionic_all.deb
        when: 
            - os_check.stdout | regex_search("Ubuntu 18")

    -   name: Install Zabbix
        command: dpkg -i /tmp/zabbix-release_{{ zabbix_version }}-1+focal_all.deb
        when: 
            - os_check.stdout | regex_search("Ubuntu 20")

    -   name: Install Zabbix
        command: rpm -Uvh /tmp/zabbix-release-{{ zabbix_version }}-1.el7.noarch.rpm
        ignore_errors: yes
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Install Zabbix
        command: rpm -Uvh /tmp/zabbix-release-{{ zabbix_version }}-1.el8.noarch.rpm
        ignore_errors: yes
        when: 
            - os_check.stdout | regex_search("CentOS Linux 8")

    -   name: Yum Clean All
        command: yum clean all
        when: 
            - os_check.stdout | regex_search("CentOS")


    -   name: Update cache
        yum: 
            name: "{{ item }}" 
        loop:
            - zabbix-server-mysql 
            - zabbix-web-mysql
            - zabbix-agent
            - zabbix-apache-conf
        when: 
            - os_check.stdout | regex_search("CentOS Linux 8")

    -   name: Update cache
        yum: 
            name: "{{ item }}" 
        loop:
            - zabbix-server-mysql 
            - zabbix-agent 
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Enable zabbix frontend
        command: yum-config-manager --enable zabbix-frontend
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Enable Frontend Yum repo
        yum: 
            name: "{{ item }}" 
        loop:
            - centos-release-scl
            - zabbix-web-mysql-scl 
            - zabbix-apache-conf-scl
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Update cache
        apt: 
            name: "{{ item }}" 
            update_cache: yes
        loop:
            - zabbix-server-mysql 
            - zabbix-frontend-php
            - zabbix-agent
        when: 
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Add libapache2-mod-php
        apt: 
            name: libapache2-mod-php 
            update_cache: yes
        when: 
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Create a new database with name 'zabbix'
        command: mysql -u root -proot -e "create database zabbix character set utf8 collate utf8_bin;"
        ignore_errors: yes
        

    -   name: Grant all Privs
        mysql_user:
            name: zabbix
            password: zabbix
            priv: 'zabbix.*:ALL,GRANT'
            state: present

    -   name: Import Schema
        shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -uzabbix -pzabbix zabbix
        ignore_errors: yes
        when: 
            - os_check.stdout | regex_search("Ubuntu")

    -   name: Execute Schema Process
        command: mysql -uroot zabbix -e "set global innodb_strict_mode='OFF';"
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Import Schema
        shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -pzabbix zabbix
        ignore_errors: yes
        when: 
            - os_check.stdout | regex_search("CentOS")

    -   name: Execute Schema Process
        command: mysql -uroot -p'root' zabbix -e "set global innodb_strict_mode='ON';"
        when: 
            - os_check.stdout | regex_search("CentOS Linux 7")
        
    -   name: Sets Zabbix conf file - Ubuntu
        become: true
        template:
            src: "zabbix.conf.j2"
            dest: "/etc/zabbix/zabbix_server.conf"
        # when:
        #         - os_check.stdout | regex_search("Ubuntu")

    -   name: Sets Apache conf file - Ubuntu
        become: true
        template:
            src: "apache.conf.j2"
            dest: "/etc/zabbix/apache.conf"
        when:
                - os_check.stdout | regex_search("Ubuntu")

    -   name: Applying PHP
        lineinfile:
            dest: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
            regexp: '^;php_value[date.timezone]'
            line: 'php_value[date.timezone] = Asia/Kolkata'
            state: present
        when:
            - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Applying PHP
        lineinfile:
            dest: /etc/php-fpm.d/zabbix.conf
            regexp: '^;php_value[date.timezone]'
            line: 'php_value[date.timezone] = Asia/Kolkata'
            state: present
        when:
            - os_check.stdout | regex_search("CentOS Linux 8")

    -   name: Create symbolic link 
        file:
            src: "/etc/zabbix/apache.conf"
            dest: "/etc/apache2/sites-enabled/apache.conf"
            state: link
        when:
                - os_check.stdout | regex_search("Ubuntu")

    # -   name: Create symbolic link 
    #     file:
    #         src: "/etc/zabbix/apache.conf"
    #         dest: "/etc/httpd/conf.d/zabbix.conf"
    #         state: link
    #     when:
    #             - os_check.stdout | regex_search("CentOS")

    -   name: Restart Apache
        service:
            name: apache2
            state: restarted
        when:
                - os_check.stdout | regex_search("Ubuntu")

    -   name: Restart Apache
        service:
            name: httpd
            state: restarted
        when:
                - os_check.stdout | regex_search("CentOS")

    -   name: Restart RH-PHP
        service:
            name: rh-php72-php-fpm
            state: restarted
        when:
                - os_check.stdout | regex_search("CentOS Linux 7")

    -   name: Restart php-fpm
        service:
            name: php-fpm
            state: restarted
        when:
                - os_check.stdout | regex_search("CentOS Linux 8")

    -   name: Ensure Zabbix Server is running and set to start on boot
        service: 
            name: zabbix-server 
            state: restarted 
            enabled: yes

    -   name: Ensure Zabbix Agent is running and set to start on boot
        service: 
            name: zabbix-agent 
            state: restarted 
            enabled: yes


    
    
